feat: digicert add setup ssm

diff --git a/.github/workflows/template.yml b/.github/workflows/template.yml
--- a/.github/workflows/template.yml
+++ b/.github/workflows/template.yml
@@ -12,9 +12,15 @@ on:
         required: false
         type: string
     secrets:
-      nugetCertificate:
+      SM_CLIENT_CERT_PASSWORD:
         required: false
-      nugetCertificatePassword:
+      SM_CLIENT_CERT_FILE_B64:
+        required: false
+      SM_HOST:
+        required: false
+      SM_API_KEY:
+        required: false
+      SM_CODE_SIGNING_CERT_SHA1_HASH:
         required: false
       nugetApiKey:
         required: false
@@ -60,7 +66,10 @@ jobs:
         name: package
         path: src/${{ inputs.projectName }}/package
   publish:
-    runs-on: ubuntu-latest
+    runs-on: ${{ matrix.os }}
+    strategy: 
+      matrix: 
+        os: [windows-latest,ubuntu-latest] 
     if: inputs.publish
     needs: [build]
     steps:
@@ -68,11 +77,41 @@ jobs:
       with:
         name: package
         path: unsigned
-    - name: Save & verify certificate
-      run: |
-        echo ${{ secrets.nugetCertificate }} | base64 -d > cert.p12
-        openssl pkcs12 -in cert.p12 -nodes -legacy -passin pass:"${{ secrets.nugetCertificatePassword }}" | openssl x509 -noout -subject -legacy || echo "Certificate validation failed"
-    - name: Sign package
-      run: dotnet nuget sign unsigned/*.nupkg --certificate-path cert.p12 --certificate-password ${{ secrets.nugetCertificatePassword }} --timestamper http://timestamp.digicert.com --output signed
+    - name: NuGet Install 
+      uses: NuGet/setup-nuget@v1.0.5 
+      with: 
+        nuget-version: latest 
+    - name: Set up certificate 
+      run: | 
+        echo "${{ secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > /d/Certificate_pkcs12.p12 
+      shell: bash
+    - name: Set variables 
+      id: variables 
+      run: | 
+        echo "::set-output name=version::${GITHUB_REF#refs/tags/v}" 
+        echo "SM_HOST=${{ secrets.SM_HOST }}" >> "$GITHUB_ENV" 
+        echo "SM_API_KEY=${{ secrets.SM_API_KEY }}" >> "$GITHUB_ENV" 
+        echo "SM_CLIENT_CERT_FILE=D:\\Certificate_pkcs12.p12" >> "$GITHUB_ENV" 
+        echo "SM_CLIENT_CERT_PASSWORD=${{ secrets.SM_CLIENT_CERT_PASSWORD }}" >> "$GITHUB_ENV" 
+        echo "C:\Program Files (x86)\Windows Kits\10\App Certification Kit" >> $GITHUB_PATH 
+        echo "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools" >> $GITHUB_PATH 
+        echo "C:\Program Files\DigiCert\DigiCert One Signing Manager Tools" >> $GITHUB_PATH 
+      shell: bash
+    - name: Setup SSM KSP on windows latest 
+      run: | 
+        curl -X GET  https://one.digicert.com/signingmanager/api-ui/v1/releases/smtools-windows-x64.msi/download -H "x-api-key:%SM_API_KEY%" -o smtools-windows-x64.msi 
+        msiexec /i smtools-windows-x64.msi /quiet /qn 
+        smksp_registrar.exe list 
+        smctl.exe keypair ls 
+        C:\Windows\System32\certutil.exe -csp "DigiCert Signing Manager KSP" -key -user 
+        smksp_cert_sync.exe 
+      shell: cmd 
+    
+    # - name: Save & verify certificate
+    #   run: |
+    #     echo ${{ secrets.nugetCertificate }} | base64 -d > cert.p12
+    #     openssl pkcs12 -in cert.p12 -nodes -legacy -passin pass:"${{ secrets.nugetCertificatePassword }}" | openssl x509 -noout -subject -legacy || echo "Certificate validation failed"
+    # - name: Sign package
+    #   run: dotnet nuget sign unsigned/*.nupkg --certificate-path cert.p12 --certificate-password ${{ secrets.nugetCertificatePassword }} --timestamper http://timestamp.digicert.com --output signed
     - name: Push package
       run: dotnet nuget push signed/${{needs.build.outputs.nupkgFilename}} --api-key ${{ secrets.nugetApiKey }} --source https://api.nuget.org/v3/index.json
